[package]
name = "panache"
version = "0.1.0"
edition = "2024"
description = "A formatter for Pandoc, Quarto, and RMarkdown documents"
license = "MIT"
repository = "https://github.com/jolars/panache"
homepage = "https://github.com/jolars/panache"
keywords = ["quarto", "pandoc", "markdown", "formatter"]
categories = ["command-line-utilities", "text-processing"]

[workspace]
members = ["crates/panache-wasm"]

[[bin]]
name = "panache"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
env_logger = "0.11.8"
regex = "1.11.2"
rowan = "0.16.1"
serde = { version = "1.0.226", features = ["derive"] }
textwrap = "0.16.2"
tokio = { version = "1", features = ["process", "rt-multi-thread", "io-util", "time", "macros", "fs"] }
toml = "0.9.6"
uuid = { version = "1.11.0", features = ["v4"] }

[dependencies.log]
version = "0.4.28"
features = ["release_max_level_info"] # disables debug/trace in release

[dev-dependencies]
similar-asserts = "1.7.0"
tokio = { version = "1", features = ["macros", "rt"] }
diff = "0.1.13"
