project:
  type: website

website:
  title: "panache"
  description: "A code formatter for Pandoc, Quarto, and RMarkdown documents"
  site-url: "https://jolars.github.io/panache/"
  repo-url: "https://github.com/jolars/panache"
  repo-actions: [edit, issue]
  search: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: playground
        text: Playground

resources:
  - "playground/**"

format:
  html:
    toc: true
    theme: cosmo

date-format: long
