project:
  type: website
  pre-render: filters/pre-render.lua
  preview:
    port: 4200

website:
  title: "panache"
  description: "A code formatter for Pandoc, Quarto, and RMarkdown documents"
  site-url: "https://jolars.github.io/panache/"
  repo-url: "https://github.com/jolars/panache"
  repo-actions: [edit, issue]
  search: true

  open-graph:
    title: "panache - A code formatter and LSP server for Pandoc, Quarto, and RMarkdown documents"
    locale: en_US

  page-footer:
    left: "panache v{{< meta version >}} | Copyright 2026, Johan Larsson"
    right:
      - icon: github
        href: "https://github.com/jolars/panache"
        aria-label: "Source for this webpage"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: playground
        text: Playground

resources:
  - "playground/**"

highlight-style: breeze

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
    html-math-method: katex
    pagetitle: "{{< meta title >}}"
    include-in-header:
      file: header.html

toc: true
date-format: "D MMMM YYYY"

filters:
  - filters/pre-render.lua
